name: "Called workflow"

on:
  workflow_call:
    inputs:
      current-env:
        required: true
        type: string
      version:
        required: true
        type: string
      app-path:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: ${{ inputs.app-name }} app for ${{ inputs.current-env }}  
    runs-on: ubuntu-latest
    environment: ${{ inputs.current-env }}
    steps:
      - name: Logging data
        run: |
            echo "version: ${{ inputs.version }}"
            echo "We are in env: ${{ inputs.current-env }} in ${{ inputs.app-path }} and ${{ inputs.app-name }}"
            echo "Secret_Key values is: ${{ secrets.SECRET_KEY }} (${{ inputs.current-env }})"
            echo "VAR_KEY value is : ${{ vars.VAR_KEY }} (${{ inputs.current-env }})"