name: "Caller Dev"

on:
  push:
    branches:
      - "*dev*"

jobs:
  versioning:
    name: Versioning
    outputs:
      version: ${{ steps.command.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: command
        run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

  applications:
    name: Get apps
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      - id: config
        run: |
          echo "config=$(jq -c '
            del(.projects.common)
            | .projects
            | to_entries
            | map({ name: .key, path: .value.root })' nest-cli.json)" >> "$GITHUB_OUTPUT"

  ReusableWorkflow:
    name: Build and Deploy (${{ matrix.target }})
    strategy:
      matrix:
        target: [development]
        application: ${{ fromJson(needs.applications.outputs.config) }}
        include:
          - version: ${{ needs.versioning.outputs.version }}

    needs: ["versioning", "applications"]
    uses: "./.github/workflows/called.yml"
    with:
      current-env: ${{ matrix.target }}
      version: ${{ matrix.version }}-${{ matrix.target }}
      app-path: ${{ matrix.application.path }}
      app-name: ${{ matrix.application.name }}
