name: "Called workflow"

on:
  workflow_call:
    inputs:
      current-env:
        required: true
        type: string
      version:
        required: true
        type: string
      applications:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.current-env }}
    strategy:
      matrix: ${{ fromJson(inputs.applications) }}
      max-parallel: 4
    steps:
      - name: Logging data
        run: |
            echo "version: ${{ inputs.version }}-${{ inputs.current-env }}"
            echo "We are in env: ${{ inputs.current-env }} in ${{ matrix.path }} and ${{ matrix.name }}"
            echo "Secret_Key values is: ${{ secrets.SECRET_KEY }} (${{ inputs.current-env }})"
            echo "VAR_KEY value is : ${{ vars.VAR_KEY }} (${{ inputs.current-env }})"