name: "Called workflow"

on:
  workflow_call:
    inputs:
      current-env:
        required: true
        type: string
      version:
        required: true
        type: string
      applications:
        required: true
        type: string
      ACR_REGISTRY:
        required: true
        type: string
      ACR_USERNAME:
        required: true
        type: string
      ACR_PASSWORD:
        required: true
        type: string
      AZURE_CREDS:
        required: true
        type: string
      CLUSTER_NAME:
        required: true
        type: string
      CLUSTER_RESOURCE_GROUP:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: ${{ matrix.name }} app for ${{ inputs.current-env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.current-env }}
    strategy:
      matrix: ${{ fromJson(inputs.applications) }}
      max-parallel: 4
    steps:
      - name: Logging data
        run: |
          echo "Let's see: ACR_REGISTRY ${{ inputs.ACR_REGISTRY }}"
          echo "Let's see: SECRETS[ACR_REGISTRY] ${{ secrets[inputs.ACR_REGISTRY] }}"
          echo "Let's see: VARS[ACR_REGISTRY] ${{ vars[inputs.ACR_REGISTRY] }}"
          echo "Let's see: VARS.YP_ACR_REGISTRY_AX ${{ vars.YP_ACR_REGISTRY_AX }}"
          echo "Let's see: VARS.YP_ACR_REGISTRY_RD ${{ vars.YP_ACR_REGISTRY_RD }}"
          echo "Let's see: ACR_USERNAME ${{ inputs.ACR_USERNAME }}"
          echo "Let's see: ACR_PASSWORD ${{ inputs.ACR_PASSWORD }}"
          echo "Let's see: AZURE_CREDS ${{ inputs.AZURE_CREDS }}"
          echo "Let's see: CLUSTER_NAME ${{ inputs.CLUSTER_NAME }}"
          echo "Let's see: CLUSTER_RESOURCE_GROUP ${{ inputs.CLUSTER_RESOURCE_GROUP }}"
          echo "version: ${{ inputs.version }}-${{ inputs.current-env }}"
          echo "We are in env: ${{ inputs.current-env }} in ${{ matrix.path }} and ${{ matrix.name }}"
          echo "Secret_Key values is: ${{ secrets.SECRET_KEY }} (${{ inputs.current-env }})"
          echo "VAR_KEY value is : ${{ vars.VAR_KEY }} (${{ inputs.current-env }})"
