name: "Caller Prod"

on:
  push:
    branches:
      - "*stable*"
    paths:
      - ".github/workflows/caller-prod.yml"

jobs:
  versioning:
    name: Versioning
    outputs:
      version: ${{ steps.command.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: command
        run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

  applications:
    name: Get apps
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      - id: config
        run: |
          echo "config=$(jq -c '
            del(.projects.common)
            | .projects
            | to_entries
            | map({ name: .key, path: .value.root })
            | { include: . }' nest-cli.json)" >> "$GITHUB_OUTPUT"

  BuildAndDeployReusable:
    name: Build and Deploy (${{ matrix.target }})
    strategy:
      matrix:
        target: [staging, production]
        include:
          - target: staging
            ACR_REGISTRY: YP_ACR_REGISTRY_AX
            ACR_USERNAME: YP_ACR_USERNAME_AX
            ACR_PASSWORD: YP_ACR_PASSWORD_AX
            AZURE_CREDS: YP_AZURE_CREDS_AX
            CLUSTER_NAME: YP_CLUSTER_NAME_AX
            CLUSTER_RESOURCE_GROUP: YP_CLUSTER_RESOURCE_GROUP_AX
          - target: production
            ACR_REGISTRY: YP_ACR_REGISTRY_RD
            ACR_USERNAME: YP_ACR_USERNAME_RD
            ACR_PASSWORD: YP_ACR_PASSWORD_RD
            AZURE_CREDS: YP_AZURE_CREDS_RD
            CLUSTER_NAME: YP_CLUSTER_NAME_RD
            CLUSTER_RESOURCE_GROUP: YP_CLUSTER_RESOURCE_GROUP_RD

    needs: ["versioning", "applications"]
    uses: "./.github/workflows/called.yml"
    with:
      current-env: ${{ matrix.target }}
      version: ${{ needs.versioning.outputs.version }}
      applications: ${{ needs.applications.outputs.config }}
      ACR_REGISTRY: ${{ matrix.ACR_REGISTRY }}
      ACR_USERNAME: ${{ matrix.ACR_USERNAME }}
      ACR_PASSWORD: ${{ matrix.ACR_PASSWORD }}
      AZURE_CREDS: ${{ matrix.AZURE_CREDS }}
      CLUSTER_NAME: ${{ matrix.CLUSTER_NAME }}
      CLUSTER_RESOURCE_GROUP: ${{ matrix.CLUSTER_RESOURCE_GROUP }}
