name: "Caller Dev"

on:
  push:
    branches:
      - "*dev*"

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [development]
    uses: "./.github/workflows/called.yml"
    with:
      current-env: ${{ matrix.target }}
